language: java
jdk: openjdk7
deploy:
  provider: cloudcontrol
  email: sjohundrudogeinn@gmail.com
  password:
    secure: oRz1RAkgkmmFFFuCta/3drJeO3a740VwNcEExtHlgZptbqQQTc3MWJJoTifqkp0LCbA1a1ja+uM14xOMOXsl+J3YTpl+MZFs5c1SAnM7JITqfN0DicPepmYe3Re9uGVqHBDMxN1PQt/bijJ7cQcKi6VhoCWkIzYBou/xUYnwXfY=
  deployment: tictacwhoop/default
  on:
    repo: oldWhoop/TicTacToe
addons:
  sauce_connect:
    username: dextroc
    access_key: 49c6e8b6-acf6-4024-a3ff-f766fa7902e4
      secure: B10QsRkvTqgZNg8xV4swbE2rT7Tk/ZJJeitK8nbfygRxuxyThz8Frc++Wj/GoX0/b0bFrKM0BpuUP+wZQd9KLEyuls1F6WGHZjZFDmjJGGDpSsybxE+TfqDSdTFyCXgCciKVLS5uVUB5RAVGasTu4eN1UJzNeyUkFl+lwPnMqU4=
