language: java
jdk: openjdk7
env:
  global:
  - secure: "DZEyzK7O5NmbdCOOJ5DS78/okAd7x1ZEoY4jf5UVnOhsNNcrENgH/MU9TPl2yWjPlvPV6Ha2pHgZ88T9D2kQNpFwiPz5wi0U4s9DU9B4yhQGzJOYMZrHCxzZ7y3GF/bB3xCHLY0OON5QL7j+H/IQMLfOWRb+rVnsIj21GUxVxtg="
  - secure: "uL3EptDgaYw+I59kz6yM13HCBrjpeHxoEHeWeeqtYbJD5xM+IVNYALJuHJkMJd41++3U3r2rlQEAvWyhe34r64ZRmUFFOohe/D5lHIKXWQCEoP9OCsT5ncrtHxLne9MgAryK67IqAU4W4Rv8Oy/ndsOG+M8PYsDqsjDmvO75EJA="
addons:
  sauce_connect:
    username: dextroc
    access_key: 49c6e8b6-acf6-4024-a3ff-f766fa7902e4
deploy:
  provider: cloudcontrol
  email: sjohundrudogeinn@gmail.com
  password:
    secure: oRz1RAkgkmmFFFuCta/3drJeO3a740VwNcEExtHlgZptbqQQTc3MWJJoTifqkp0LCbA1a1ja+uM14xOMOXsl+J3YTpl+MZFs5c1SAnM7JITqfN0DicPepmYe3Re9uGVqHBDMxN1PQt/bijJ7cQcKi6VhoCWkIzYBou/xUYnwXfY=
  deployment: tictacwhoop/default
  on:
    repo: oldWhoop/TicTacToe
after_deploy:
- mvn integration-test

