language: java
jdk: openjdk7
addons:
  sauce_connect:
    username: dextroc
    access_key: 49c6e8b6-acf6-4024-a3ff-f766fa7902e4
deploy:
  provider: cloudcontrol
  email: sjohundrudogeinn@gmail.com
  password:
    secure: oRz1RAkgkmmFFFuCta/3drJeO3a740VwNcEExtHlgZptbqQQTc3MWJJoTifqkp0LCbA1a1ja+uM14xOMOXsl+J3YTpl+MZFs5c1SAnM7JITqfN0DicPepmYe3Re9uGVqHBDMxN1PQt/bijJ7cQcKi6VhoCWkIzYBou/xUYnwXfY=
  deployment: tictacwhoop/default
  on:
    repo: oldWhoop/TicTacToe
after_deploy:
- mvn integration-test
- wget -r ftp://46.149.28.9/ --user $FTP_USER --password $FTP_PASSWORD
env:
  global:
  - secure: IRjkSZindWBf2h3eHG/GqLNxKpxk2Y7+Ix+U+Iy17xwt6TKz+hY8awKGKKCE82eYOOQE/hg+4F5jh2chjlwCCStr9o3T00y1aJQ51Kti3+sIWZrVBeRhcFkEq9j6lYx1fqb5Eo7TXBLUYV5AkFNCrL+nm69BLV6wppFvdmwSDqs=
  - secure: WGQ1oxzx231pPFhB/bxgz4BddbGvjIqRw/lLcY4k92DotPJ67lpIpQMIfBHppqfMbsthcJcvAe5L6r4qydBe6YPhr/9pMHPxw5A69vszyFGKyZGKrfVYvGVpFo3gCKboXZC1JKRV914pF03pmjjbVzM5pfjumqwCKy6TjsRku9o=
