language: java
jdk: openjdk7
deploy:
  provider: cloudcontrol
  email: sjohundrudogeinn@gmail.com
  password:
    secure: oRz1RAkgkmmFFFuCta/3drJeO3a740VwNcEExtHlgZptbqQQTc3MWJJoTifqkp0LCbA1a1ja+uM14xOMOXsl+J3YTpl+MZFs5c1SAnM7JITqfN0DicPepmYe3Re9uGVqHBDMxN1PQt/bijJ7cQcKi6VhoCWkIzYBou/xUYnwXfY=
  deployment: tictacwhoop/default
  on:
    repo: oldWhoop/TicTacToe
addons:
  sauce_connect:
    username: dextroc
    access_key:
    secure: OD2NTSZmVJSSQbCCBHHSszRt5Y/X885DbwAWM/HDEUFLKnC6oaOr3jP9eanSSBzaRtUkW7qLR6QfakiuG6AabA1bGgpXQC35AbI5pgDSK0cKUFuUIjWx2++hUhugGVOHQcDO1XXuFqWmWPtf+6guwUzxvmeoBVMlVxu8bEhLaBY=
