language: java
jdk: openjdk7
addons:
  sauce_connect:
    username: johannj12
    access_key: f1bb82b1-19a6-4dc8-a40b-165bb170379e
deploy:
  provider: cloudcontrol
  email: sjohundrudogeinn@gmail.com
  password:
    secure: oRz1RAkgkmmFFFuCta/3drJeO3a740VwNcEExtHlgZptbqQQTc3MWJJoTifqkp0LCbA1a1ja+uM14xOMOXsl+J3YTpl+MZFs5c1SAnM7JITqfN0DicPepmYe3Re9uGVqHBDMxN1PQt/bijJ7cQcKi6VhoCWkIzYBou/xUYnwXfY=
  deployment: tictacwhoop/default
  on:
    repo: oldWhoop/TicTacToe
after_deploy:
- mvn integration-test